// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: acs11.proto
// </auto-generated>
// Original file comments:
// *
// AElf Standards ACS11(Consensus Standard)
//
// Used to customize consensus mechanisms for cross chain.
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Standards.ACS11 {

  #region Events
  #endregion
  internal static partial class CrossChainInteractionContractContainer
  {
    static readonly string __ServiceName = "acs11.CrossChainInteractionContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BytesValue> __Marshaller_google_protobuf_BytesValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BytesValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.BytesValue, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateInformationFromCrossChain = new aelf::Method<global::Google.Protobuf.WellKnownTypes.BytesValue, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdateInformationFromCrossChain",
        __Marshaller_google_protobuf_BytesValue,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.BytesValue, global::Google.Protobuf.WellKnownTypes.BytesValue> __Method_GetChainInitializationInformation = new aelf::Method<global::Google.Protobuf.WellKnownTypes.BytesValue, global::Google.Protobuf.WellKnownTypes.BytesValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetChainInitializationInformation",
        __Marshaller_google_protobuf_BytesValue,
        __Marshaller_google_protobuf_BytesValue);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_CheckCrossChainIndexingPermission = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "CheckCrossChainIndexingPermission",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_BoolValue);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Standards.ACS11.Acs11Reflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS11.Acs11Reflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    public class CrossChainInteractionContractReferenceState : global::AElf.Sdk.CSharp.State.ContractReferenceState
    {
      internal global::AElf.Sdk.CSharp.State.MethodReference<global::Google.Protobuf.WellKnownTypes.BytesValue, global::Google.Protobuf.WellKnownTypes.Empty> UpdateInformationFromCrossChain { get; set; }
      internal global::AElf.Sdk.CSharp.State.MethodReference<global::Google.Protobuf.WellKnownTypes.BytesValue, global::Google.Protobuf.WellKnownTypes.BytesValue> GetChainInitializationInformation { get; set; }
      internal global::AElf.Sdk.CSharp.State.MethodReference<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue> CheckCrossChainIndexingPermission { get; set; }
    }
  }
}
#endregion

