// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: acs11.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf.Standards.ACS11 {

  /// <summary>Holder for reflection information generated from acs11.proto</summary>
  internal static partial class Acs11Reflection {

    #region Descriptor
    /// <summary>File descriptor for acs11.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Acs11Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgthY3MxMS5wcm90bxIFYWNzMTEaEmFlbGYvb3B0aW9ucy5wcm90bxoPYWVs",
            "Zi9jb3JlLnByb3RvGh5nb29nbGUvcHJvdG9idWYvd3JhcHBlcnMucHJvdG8a",
            "G2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bzK2AgodQ3Jvc3NDaGFpbklu",
            "dGVyYWN0aW9uQ29udHJhY3QSWAofVXBkYXRlSW5mb3JtYXRpb25Gcm9tQ3Jv",
            "c3NDaGFpbhIbLmdvb2dsZS5wcm90b2J1Zi5CeXRlc1ZhbHVlGhYuZ29vZ2xl",
            "LnByb3RvYnVmLkVtcHR5IgASZAohR2V0Q2hhaW5Jbml0aWFsaXphdGlvbklu",
            "Zm9ybWF0aW9uEhsuZ29vZ2xlLnByb3RvYnVmLkJ5dGVzVmFsdWUaGy5nb29n",
            "bGUucHJvdG9idWYuQnl0ZXNWYWx1ZSIFiIn3AQESVQohQ2hlY2tDcm9zc0No",
            "YWluSW5kZXhpbmdQZXJtaXNzaW9uEg0uYWVsZi5BZGRyZXNzGhouZ29vZ2xl",
            "LnByb3RvYnVmLkJvb2xWYWx1ZSIFiIn3AQFCIaoCFEFFbGYuU3RhbmRhcmRz",
            "LkFDUzExipL0AQVhY3MxMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.OptionsReflection.Descriptor, global::AElf.Types.CoreReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
