// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: acs7.proto
// </auto-generated>
// Original file comments:
// *
// AElf Standards ACS7(Contract CrossChain Standard)
//
// ACS7 is for cross chain related contract implementation.
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Standards.ACS7 {

  #region Events
  public partial class SideChainBlockDataIndexed : aelf::IEvent<SideChainBlockDataIndexed>
  {
    public global::System.Collections.Generic.IEnumerable<SideChainBlockDataIndexed> GetIndexed()
    {
      return new List<SideChainBlockDataIndexed>
      {
      };
    }

    public SideChainBlockDataIndexed GetNonIndexed()
    {
      return new SideChainBlockDataIndexed
      {
      };
    }
  }

  public partial class CrossChainIndexingDataProposedEvent : aelf::IEvent<CrossChainIndexingDataProposedEvent>
  {
    public global::System.Collections.Generic.IEnumerable<CrossChainIndexingDataProposedEvent> GetIndexed()
    {
      return new List<CrossChainIndexingDataProposedEvent>
      {
      };
    }

    public CrossChainIndexingDataProposedEvent GetNonIndexed()
    {
      return new CrossChainIndexingDataProposedEvent
      {
        ProposedCrossChainData = ProposedCrossChainData,
        ProposalId = ProposalId,
      };
    }
  }

  #endregion
}
#endregion

