// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ca_contract.proto
// </auto-generated>
// Original file comments:
// *
// CA contract.
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Portkey.Contracts.CA {

  #region Events
  public partial class CAHolderCreated : aelf::IEvent<CAHolderCreated>
  {
    public global::System.Collections.Generic.IEnumerable<CAHolderCreated> GetIndexed()
    {
      return new List<CAHolderCreated>
      {
      new CAHolderCreated
      {
        Creator = Creator
      },
      new CAHolderCreated
      {
        CaHash = CaHash
      },
      new CAHolderCreated
      {
        CaAddress = CaAddress
      },
      new CAHolderCreated
      {
        Manager = Manager
      },
      };
    }

    public CAHolderCreated GetNonIndexed()
    {
      return new CAHolderCreated
      {
        ExtraData = ExtraData,
      };
    }
  }

  public partial class GuardianAdded : aelf::IEvent<GuardianAdded>
  {
    public global::System.Collections.Generic.IEnumerable<GuardianAdded> GetIndexed()
    {
      return new List<GuardianAdded>
      {
      new GuardianAdded
      {
        CaHash = CaHash
      },
      };
    }

    public GuardianAdded GetNonIndexed()
    {
      return new GuardianAdded
      {
        CaAddress = CaAddress,
        GuardianAdded_ = GuardianAdded_,
        GuardiansMerkleTreeRoot = GuardiansMerkleTreeRoot,
      };
    }
  }

  public partial class GuardianRemoved : aelf::IEvent<GuardianRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<GuardianRemoved> GetIndexed()
    {
      return new List<GuardianRemoved>
      {
      new GuardianRemoved
      {
        CaHash = CaHash
      },
      };
    }

    public GuardianRemoved GetNonIndexed()
    {
      return new GuardianRemoved
      {
        CaAddress = CaAddress,
        GuardianRemoved_ = GuardianRemoved_,
        GuardiansMerkleTreeRoot = GuardiansMerkleTreeRoot,
      };
    }
  }

  public partial class GuardianUpdated : aelf::IEvent<GuardianUpdated>
  {
    public global::System.Collections.Generic.IEnumerable<GuardianUpdated> GetIndexed()
    {
      return new List<GuardianUpdated>
      {
      new GuardianUpdated
      {
        CaHash = CaHash
      },
      };
    }

    public GuardianUpdated GetNonIndexed()
    {
      return new GuardianUpdated
      {
        CaAddress = CaAddress,
        GuardianUpdatedPre = GuardianUpdatedPre,
        GuardianUpdatedNew = GuardianUpdatedNew,
        GuardiansMerkleTreeRoot = GuardiansMerkleTreeRoot,
      };
    }
  }

  public partial class LoginGuardianAdded : aelf::IEvent<LoginGuardianAdded>
  {
    public global::System.Collections.Generic.IEnumerable<LoginGuardianAdded> GetIndexed()
    {
      return new List<LoginGuardianAdded>
      {
      new LoginGuardianAdded
      {
        CaHash = CaHash
      },
      new LoginGuardianAdded
      {
        Manager = Manager
      },
      new LoginGuardianAdded
      {
        LoginGuardian = LoginGuardian
      },
      };
    }

    public LoginGuardianAdded GetNonIndexed()
    {
      return new LoginGuardianAdded
      {
        CaAddress = CaAddress,
      };
    }
  }

  public partial class ManagerInfoSocialRecovered : aelf::IEvent<ManagerInfoSocialRecovered>
  {
    public global::System.Collections.Generic.IEnumerable<ManagerInfoSocialRecovered> GetIndexed()
    {
      return new List<ManagerInfoSocialRecovered>
      {
      new ManagerInfoSocialRecovered
      {
        CaHash = CaHash
      },
      new ManagerInfoSocialRecovered
      {
        CaAddress = CaAddress
      },
      new ManagerInfoSocialRecovered
      {
        Manager = Manager
      },
      };
    }

    public ManagerInfoSocialRecovered GetNonIndexed()
    {
      return new ManagerInfoSocialRecovered
      {
        ExtraData = ExtraData,
      };
    }
  }

  public partial class ManagerInfoAdded : aelf::IEvent<ManagerInfoAdded>
  {
    public global::System.Collections.Generic.IEnumerable<ManagerInfoAdded> GetIndexed()
    {
      return new List<ManagerInfoAdded>
      {
      new ManagerInfoAdded
      {
        CaHash = CaHash
      },
      new ManagerInfoAdded
      {
        CaAddress = CaAddress
      },
      new ManagerInfoAdded
      {
        Manager = Manager
      },
      };
    }

    public ManagerInfoAdded GetNonIndexed()
    {
      return new ManagerInfoAdded
      {
        ExtraData = ExtraData,
      };
    }
  }

  public partial class ManagerInfoRemoved : aelf::IEvent<ManagerInfoRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<ManagerInfoRemoved> GetIndexed()
    {
      return new List<ManagerInfoRemoved>
      {
      new ManagerInfoRemoved
      {
        CaHash = CaHash
      },
      new ManagerInfoRemoved
      {
        CaAddress = CaAddress
      },
      new ManagerInfoRemoved
      {
        Manager = Manager
      },
      };
    }

    public ManagerInfoRemoved GetNonIndexed()
    {
      return new ManagerInfoRemoved
      {
        ExtraData = ExtraData,
      };
    }
  }

  public partial class ManagerInfoUpdated : aelf::IEvent<ManagerInfoUpdated>
  {
    public global::System.Collections.Generic.IEnumerable<ManagerInfoUpdated> GetIndexed()
    {
      return new List<ManagerInfoUpdated>
      {
      new ManagerInfoUpdated
      {
        CaHash = CaHash
      },
      new ManagerInfoUpdated
      {
        CaAddress = CaAddress
      },
      new ManagerInfoUpdated
      {
        Manager = Manager
      },
      };
    }

    public ManagerInfoUpdated GetNonIndexed()
    {
      return new ManagerInfoUpdated
      {
        ExtraData = ExtraData,
      };
    }
  }

  public partial class LoginGuardianUnbound : aelf::IEvent<LoginGuardianUnbound>
  {
    public global::System.Collections.Generic.IEnumerable<LoginGuardianUnbound> GetIndexed()
    {
      return new List<LoginGuardianUnbound>
      {
      new LoginGuardianUnbound
      {
        CaHash = CaHash
      },
      new LoginGuardianUnbound
      {
        Manager = Manager
      },
      new LoginGuardianUnbound
      {
        LoginGuardianIdentifierHash = LoginGuardianIdentifierHash
      },
      };
    }

    public LoginGuardianUnbound GetNonIndexed()
    {
      return new LoginGuardianUnbound
      {
        CaAddress = CaAddress,
      };
    }
  }

  public partial class LoginGuardianRemoved : aelf::IEvent<LoginGuardianRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<LoginGuardianRemoved> GetIndexed()
    {
      return new List<LoginGuardianRemoved>
      {
      new LoginGuardianRemoved
      {
        CaHash = CaHash
      },
      new LoginGuardianRemoved
      {
        Manager = Manager
      },
      new LoginGuardianRemoved
      {
        LoginGuardian = LoginGuardian
      },
      };
    }

    public LoginGuardianRemoved GetNonIndexed()
    {
      return new LoginGuardianRemoved
      {
        CaAddress = CaAddress,
      };
    }
  }

  public partial class VerifierServerEndPointsAdded : aelf::IEvent<VerifierServerEndPointsAdded>
  {
    public global::System.Collections.Generic.IEnumerable<VerifierServerEndPointsAdded> GetIndexed()
    {
      return new List<VerifierServerEndPointsAdded>
      {
      new VerifierServerEndPointsAdded
      {
        VerifierServer = VerifierServer
      },
      };
    }

    public VerifierServerEndPointsAdded GetNonIndexed()
    {
      return new VerifierServerEndPointsAdded
      {
      };
    }
  }

  public partial class VerifierServerEndPointsRemoved : aelf::IEvent<VerifierServerEndPointsRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<VerifierServerEndPointsRemoved> GetIndexed()
    {
      return new List<VerifierServerEndPointsRemoved>
      {
      new VerifierServerEndPointsRemoved
      {
        VerifierServer = VerifierServer
      },
      };
    }

    public VerifierServerEndPointsRemoved GetNonIndexed()
    {
      return new VerifierServerEndPointsRemoved
      {
      };
    }
  }

  public partial class VerifierServerRemoved : aelf::IEvent<VerifierServerRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<VerifierServerRemoved> GetIndexed()
    {
      return new List<VerifierServerRemoved>
      {
      new VerifierServerRemoved
      {
        VerifierServer = VerifierServer
      },
      };
    }

    public VerifierServerRemoved GetNonIndexed()
    {
      return new VerifierServerRemoved
      {
      };
    }
  }

  public partial class CAServerAdded : aelf::IEvent<CAServerAdded>
  {
    public global::System.Collections.Generic.IEnumerable<CAServerAdded> GetIndexed()
    {
      return new List<CAServerAdded>
      {
      };
    }

    public CAServerAdded GetNonIndexed()
    {
      return new CAServerAdded
      {
        CaSeverAdded = CaSeverAdded,
      };
    }
  }

  public partial class CAServerRemoved : aelf::IEvent<CAServerRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<CAServerRemoved> GetIndexed()
    {
      return new List<CAServerRemoved>
      {
      };
    }

    public CAServerRemoved GetNonIndexed()
    {
      return new CAServerRemoved
      {
        CaServerRemoved = CaServerRemoved,
      };
    }
  }

  public partial class CAHolderSynced : aelf::IEvent<CAHolderSynced>
  {
    public global::System.Collections.Generic.IEnumerable<CAHolderSynced> GetIndexed()
    {
      return new List<CAHolderSynced>
      {
      new CAHolderSynced
      {
        Creator = Creator
      },
      new CAHolderSynced
      {
        CaHash = CaHash
      },
      new CAHolderSynced
      {
        CaAddress = CaAddress
      },
      new CAHolderSynced
      {
        ManagerInfosAdded = ManagerInfosAdded
      },
      new CAHolderSynced
      {
        ManagerInfosRemoved = ManagerInfosRemoved
      },
      new CAHolderSynced
      {
        LoginGuardiansAdded = LoginGuardiansAdded
      },
      new CAHolderSynced
      {
        LoginGuardiansUnbound = LoginGuardiansUnbound
      },
      };
    }

    public CAHolderSynced GetNonIndexed()
    {
      return new CAHolderSynced
      {
      };
    }
  }

  public partial class CreatorControllerAdded : aelf::IEvent<CreatorControllerAdded>
  {
    public global::System.Collections.Generic.IEnumerable<CreatorControllerAdded> GetIndexed()
    {
      return new List<CreatorControllerAdded>
      {
      new CreatorControllerAdded
      {
        Address = Address
      },
      };
    }

    public CreatorControllerAdded GetNonIndexed()
    {
      return new CreatorControllerAdded
      {
      };
    }
  }

  public partial class CreatorControllerRemoved : aelf::IEvent<CreatorControllerRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<CreatorControllerRemoved> GetIndexed()
    {
      return new List<CreatorControllerRemoved>
      {
      new CreatorControllerRemoved
      {
        Address = Address
      },
      };
    }

    public CreatorControllerRemoved GetNonIndexed()
    {
      return new CreatorControllerRemoved
      {
      };
    }
  }

  public partial class ServerControllerAdded : aelf::IEvent<ServerControllerAdded>
  {
    public global::System.Collections.Generic.IEnumerable<ServerControllerAdded> GetIndexed()
    {
      return new List<ServerControllerAdded>
      {
      new ServerControllerAdded
      {
        Address = Address
      },
      };
    }

    public ServerControllerAdded GetNonIndexed()
    {
      return new ServerControllerAdded
      {
      };
    }
  }

  public partial class ServerControllerRemoved : aelf::IEvent<ServerControllerRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<ServerControllerRemoved> GetIndexed()
    {
      return new List<ServerControllerRemoved>
      {
      new ServerControllerRemoved
      {
        Address = Address
      },
      };
    }

    public ServerControllerRemoved GetNonIndexed()
    {
      return new ServerControllerRemoved
      {
      };
    }
  }

  public partial class AdminChanged : aelf::IEvent<AdminChanged>
  {
    public global::System.Collections.Generic.IEnumerable<AdminChanged> GetIndexed()
    {
      return new List<AdminChanged>
      {
      new AdminChanged
      {
        Address = Address
      },
      };
    }

    public AdminChanged GetNonIndexed()
    {
      return new AdminChanged
      {
      };
    }
  }

  public partial class ManagerApproved : aelf::IEvent<ManagerApproved>
  {
    public global::System.Collections.Generic.IEnumerable<ManagerApproved> GetIndexed()
    {
      return new List<ManagerApproved>
      {
      };
    }

    public ManagerApproved GetNonIndexed()
    {
      return new ManagerApproved
      {
        CaHash = CaHash,
        Spender = Spender,
        Symbol = Symbol,
        Amount = Amount,
        External = External,
      };
    }
  }

  public partial class TransferLimitChanged : aelf::IEvent<TransferLimitChanged>
  {
    public global::System.Collections.Generic.IEnumerable<TransferLimitChanged> GetIndexed()
    {
      return new List<TransferLimitChanged>
      {
      new TransferLimitChanged
      {
        CaHash = CaHash
      },
      new TransferLimitChanged
      {
        Symbol = Symbol
      },
      new TransferLimitChanged
      {
        SingleLimit = SingleLimit
      },
      new TransferLimitChanged
      {
        DailyLimit = DailyLimit
      },
      };
    }

    public TransferLimitChanged GetNonIndexed()
    {
      return new TransferLimitChanged
      {
      };
    }
  }

  #endregion
  public static partial class CAContractContainer
  {
    static readonly string __ServiceName = "ca.CAContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.InitializeInput> __Marshaller_ca_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.CreateCAHolderInput> __Marshaller_ca_CreateCAHolderInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.CreateCAHolderInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddGuardianInput> __Marshaller_ca_AddGuardianInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddGuardianInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveGuardianInput> __Marshaller_ca_RemoveGuardianInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveGuardianInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.UpdateGuardianInput> __Marshaller_ca_UpdateGuardianInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.UpdateGuardianInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetGuardianForLoginInput> __Marshaller_ca_SetGuardianForLoginInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetGuardianForLoginInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.UnsetGuardianForLoginInput> __Marshaller_ca_UnsetGuardianForLoginInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.UnsetGuardianForLoginInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerForwardCallInput> __Marshaller_ca_ManagerForwardCallInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerForwardCallInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerTransferInput> __Marshaller_ca_ManagerTransferInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerTransferInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerTransferFromInput> __Marshaller_ca_ManagerTransferFromInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerTransferFromInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SocialRecoveryInput> __Marshaller_ca_SocialRecoveryInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SocialRecoveryInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddManagerInfoInput> __Marshaller_ca_AddManagerInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddManagerInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveManagerInfoInput> __Marshaller_ca_RemoveManagerInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveManagerInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveOtherManagerInfoInput> __Marshaller_ca_RemoveOtherManagerInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveOtherManagerInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.UpdateManagerInfosInput> __Marshaller_ca_UpdateManagerInfosInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.UpdateManagerInfosInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddVerifierServerEndPointsInput> __Marshaller_ca_AddVerifierServerEndPointsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddVerifierServerEndPointsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveVerifierServerEndPointsInput> __Marshaller_ca_RemoveVerifierServerEndPointsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveVerifierServerEndPointsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveVerifierServerInput> __Marshaller_ca_RemoveVerifierServerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveVerifierServerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddCAServerInput> __Marshaller_ca_AddCAServerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddCAServerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.RemoveCAServerInput> __Marshaller_ca_RemoveCAServerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.RemoveCAServerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetHolderInfoInput> __Marshaller_ca_GetHolderInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetHolderInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetHolderInfoOutput> __Marshaller_ca_GetHolderInfoOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetHolderInfoOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetVerifierServersOutput> __Marshaller_ca_GetVerifierServersOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetVerifierServersOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetCAServersOutput> __Marshaller_ca_GetCAServersOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetCAServersOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ValidateCAHolderInfoWithManagerInfosExistsInput> __Marshaller_ca_ValidateCAHolderInfoWithManagerInfosExistsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ValidateCAHolderInfoWithManagerInfosExistsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SyncHolderInfoInput> __Marshaller_ca_SyncHolderInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SyncHolderInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ValidateStrategyInput> __Marshaller_ca_ValidateStrategyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ValidateStrategyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ValidateStrategyOutput> __Marshaller_ca_ValidateStrategyOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ValidateStrategyOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetContractDelegationFeeInput> __Marshaller_ca_SetContractDelegationFeeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetContractDelegationFeeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetContractDelegationFeeOutput> __Marshaller_ca_GetContractDelegationFeeOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetContractDelegationFeeOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ControllerInput> __Marshaller_ca_ControllerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ControllerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ControllerOutput> __Marshaller_ca_ControllerOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ControllerOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AdminInput> __Marshaller_ca_AdminInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AdminInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AdminOutput> __Marshaller_ca_AdminOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AdminOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.OperationTypeInSignatureEnabledInput> __Marshaller_ca_OperationTypeInSignatureEnabledInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.OperationTypeInSignatureEnabledInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetCAContractAddressesInput> __Marshaller_ca_SetCAContractAddressesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetCAContractAddressesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.AddVerifierIdMapperInput> __Marshaller_ca_AddVerifierIdMapperInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.AddVerifierIdMapperInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerApproveInput> __Marshaller_ca_ManagerApproveInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerApproveInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetTransferLimitInput> __Marshaller_ca_SetTransferLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetTransferLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetTransferLimitInput> __Marshaller_caimpl_GetTransferLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetTransferLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetTransferLimitOutput> __Marshaller_caimpl_GetTransferLimitOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetTransferLimitOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetDefaultTokenTransferLimitInput> __Marshaller_caimpl_SetDefaultTokenTransferLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetDefaultTokenTransferLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitInput> __Marshaller_caimpl_GetDefaultTokenTransferLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitOutput> __Marshaller_caimpl_GetDefaultTokenTransferLimitOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.SetForbiddenForwardCallContractMethodInput> __Marshaller_caimpl_SetForbiddenForwardCallContractMethodInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.SetForbiddenForwardCallContractMethodInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Portkey.Contracts.CA.ManagerApproveForbiddenEnabledInput> __Marshaller_caimpl_ManagerApproveForbiddenEnabledInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Portkey.Contracts.CA.ManagerApproveForbiddenEnabledInput.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Portkey.Contracts.CA.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Portkey.Contracts.CA.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_ca_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.CreateCAHolderInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CreateCAHolder = new aelf::Method<global::Portkey.Contracts.CA.CreateCAHolderInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CreateCAHolder",
        __Marshaller_ca_CreateCAHolderInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddGuardian = new aelf::Method<global::Portkey.Contracts.CA.AddGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddGuardian",
        __Marshaller_ca_AddGuardianInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveGuardian = new aelf::Method<global::Portkey.Contracts.CA.RemoveGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveGuardian",
        __Marshaller_ca_RemoveGuardianInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.UpdateGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateGuardian = new aelf::Method<global::Portkey.Contracts.CA.UpdateGuardianInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdateGuardian",
        __Marshaller_ca_UpdateGuardianInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetGuardianForLoginInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetGuardianForLogin = new aelf::Method<global::Portkey.Contracts.CA.SetGuardianForLoginInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetGuardianForLogin",
        __Marshaller_ca_SetGuardianForLoginInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.UnsetGuardianForLoginInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UnsetGuardianForLogin = new aelf::Method<global::Portkey.Contracts.CA.UnsetGuardianForLoginInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UnsetGuardianForLogin",
        __Marshaller_ca_UnsetGuardianForLoginInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerForwardCallInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ManagerForwardCall = new aelf::Method<global::Portkey.Contracts.CA.ManagerForwardCallInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ManagerForwardCall",
        __Marshaller_ca_ManagerForwardCallInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerTransferInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ManagerTransfer = new aelf::Method<global::Portkey.Contracts.CA.ManagerTransferInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ManagerTransfer",
        __Marshaller_ca_ManagerTransferInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerTransferFromInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ManagerTransferFrom = new aelf::Method<global::Portkey.Contracts.CA.ManagerTransferFromInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ManagerTransferFrom",
        __Marshaller_ca_ManagerTransferFromInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SocialRecoveryInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SocialRecovery = new aelf::Method<global::Portkey.Contracts.CA.SocialRecoveryInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SocialRecovery",
        __Marshaller_ca_SocialRecoveryInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddManagerInfo = new aelf::Method<global::Portkey.Contracts.CA.AddManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddManagerInfo",
        __Marshaller_ca_AddManagerInfoInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveManagerInfo = new aelf::Method<global::Portkey.Contracts.CA.RemoveManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveManagerInfo",
        __Marshaller_ca_RemoveManagerInfoInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveOtherManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveOtherManagerInfo = new aelf::Method<global::Portkey.Contracts.CA.RemoveOtherManagerInfoInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveOtherManagerInfo",
        __Marshaller_ca_RemoveOtherManagerInfoInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.UpdateManagerInfosInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateManagerInfos = new aelf::Method<global::Portkey.Contracts.CA.UpdateManagerInfosInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdateManagerInfos",
        __Marshaller_ca_UpdateManagerInfosInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddVerifierServerEndPointsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddVerifierServerEndPoints = new aelf::Method<global::Portkey.Contracts.CA.AddVerifierServerEndPointsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddVerifierServerEndPoints",
        __Marshaller_ca_AddVerifierServerEndPointsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveVerifierServerEndPointsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveVerifierServerEndPoints = new aelf::Method<global::Portkey.Contracts.CA.RemoveVerifierServerEndPointsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveVerifierServerEndPoints",
        __Marshaller_ca_RemoveVerifierServerEndPointsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveVerifierServerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveVerifierServer = new aelf::Method<global::Portkey.Contracts.CA.RemoveVerifierServerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveVerifierServer",
        __Marshaller_ca_RemoveVerifierServerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddCAServerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddCAServer = new aelf::Method<global::Portkey.Contracts.CA.AddCAServerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddCAServer",
        __Marshaller_ca_AddCAServerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.RemoveCAServerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveCAServer = new aelf::Method<global::Portkey.Contracts.CA.RemoveCAServerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveCAServer",
        __Marshaller_ca_RemoveCAServerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.GetHolderInfoInput, global::Portkey.Contracts.CA.GetHolderInfoOutput> __Method_GetHolderInfo = new aelf::Method<global::Portkey.Contracts.CA.GetHolderInfoInput, global::Portkey.Contracts.CA.GetHolderInfoOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetHolderInfo",
        __Marshaller_ca_GetHolderInfoInput,
        __Marshaller_ca_GetHolderInfoOutput);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetVerifierServersOutput> __Method_GetVerifierServers = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetVerifierServersOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVerifierServers",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ca_GetVerifierServersOutput);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetCAServersOutput> __Method_GetCAServers = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetCAServersOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCAServers",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ca_GetCAServersOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ValidateCAHolderInfoWithManagerInfosExistsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ValidateCAHolderInfoWithManagerInfosExists = new aelf::Method<global::Portkey.Contracts.CA.ValidateCAHolderInfoWithManagerInfosExistsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ValidateCAHolderInfoWithManagerInfosExists",
        __Marshaller_ca_ValidateCAHolderInfoWithManagerInfosExistsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SyncHolderInfoInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SyncHolderInfo = new aelf::Method<global::Portkey.Contracts.CA.SyncHolderInfoInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SyncHolderInfo",
        __Marshaller_ca_SyncHolderInfoInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ValidateStrategyInput, global::Portkey.Contracts.CA.ValidateStrategyOutput> __Method_ValidateStrategy = new aelf::Method<global::Portkey.Contracts.CA.ValidateStrategyInput, global::Portkey.Contracts.CA.ValidateStrategyOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "ValidateStrategy",
        __Marshaller_ca_ValidateStrategyInput,
        __Marshaller_ca_ValidateStrategyOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetContractDelegationFeeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetContractDelegationFee = new aelf::Method<global::Portkey.Contracts.CA.SetContractDelegationFeeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetContractDelegationFee",
        __Marshaller_ca_SetContractDelegationFeeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetContractDelegationFeeOutput> __Method_GetContractDelegationFee = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.GetContractDelegationFeeOutput>(
        aelf::MethodType.Action,
        __ServiceName,
        "GetContractDelegationFee",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ca_GetContractDelegationFeeOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddCreatorController = new aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddCreatorController",
        __Marshaller_ca_ControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveCreatorController = new aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveCreatorController",
        __Marshaller_ca_ControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.ControllerOutput> __Method_GetCreatorControllers = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.ControllerOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCreatorControllers",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ca_ControllerOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddServerController = new aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddServerController",
        __Marshaller_ca_ControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveServerController = new aelf::Method<global::Portkey.Contracts.CA.ControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveServerController",
        __Marshaller_ca_ControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.ControllerOutput> __Method_GetServerControllers = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.ControllerOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetServerControllers",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ca_ControllerOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AdminInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeAdmin = new aelf::Method<global::Portkey.Contracts.CA.AdminInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeAdmin",
        __Marshaller_ca_AdminInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.AdminOutput> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Portkey.Contracts.CA.AdminOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ca_AdminOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.OperationTypeInSignatureEnabledInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeOperationTypeInSignatureEnabled = new aelf::Method<global::Portkey.Contracts.CA.OperationTypeInSignatureEnabledInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeOperationTypeInSignatureEnabled",
        __Marshaller_ca_OperationTypeInSignatureEnabledInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetCAContractAddressesInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetCAContractAddresses = new aelf::Method<global::Portkey.Contracts.CA.SetCAContractAddressesInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetCAContractAddresses",
        __Marshaller_ca_SetCAContractAddressesInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.AddVerifierIdMapperInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddVerifierIdMapper = new aelf::Method<global::Portkey.Contracts.CA.AddVerifierIdMapperInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddVerifierIdMapper",
        __Marshaller_ca_AddVerifierIdMapperInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerApproveInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ManagerApprove = new aelf::Method<global::Portkey.Contracts.CA.ManagerApproveInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ManagerApprove",
        __Marshaller_ca_ManagerApproveInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetTransferLimitInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetTransferLimit = new aelf::Method<global::Portkey.Contracts.CA.SetTransferLimitInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetTransferLimit",
        __Marshaller_ca_SetTransferLimitInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.GetTransferLimitInput, global::Portkey.Contracts.CA.GetTransferLimitOutput> __Method_GetTransferLimit = new aelf::Method<global::Portkey.Contracts.CA.GetTransferLimitInput, global::Portkey.Contracts.CA.GetTransferLimitOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransferLimit",
        __Marshaller_caimpl_GetTransferLimitInput,
        __Marshaller_caimpl_GetTransferLimitOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetDefaultTokenTransferLimitInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetDefaultTokenTransferLimit = new aelf::Method<global::Portkey.Contracts.CA.SetDefaultTokenTransferLimitInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetDefaultTokenTransferLimit",
        __Marshaller_caimpl_SetDefaultTokenTransferLimitInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitInput, global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitOutput> __Method_GetDefaultTokenTransferLimit = new aelf::Method<global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitInput, global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetDefaultTokenTransferLimit",
        __Marshaller_caimpl_GetDefaultTokenTransferLimitInput,
        __Marshaller_caimpl_GetDefaultTokenTransferLimitOutput);

    static readonly aelf::Method<global::Portkey.Contracts.CA.SetForbiddenForwardCallContractMethodInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetForbiddenForwardCallContractMethod = new aelf::Method<global::Portkey.Contracts.CA.SetForbiddenForwardCallContractMethodInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetForbiddenForwardCallContractMethod",
        __Marshaller_caimpl_SetForbiddenForwardCallContractMethodInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Portkey.Contracts.CA.ManagerApproveForbiddenEnabledInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeManagerApproveForbiddenEnabled = new aelf::Method<global::Portkey.Contracts.CA.ManagerApproveForbiddenEnabledInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeManagerApproveForbiddenEnabled",
        __Marshaller_caimpl_ManagerApproveForbiddenEnabledInput,
        __Marshaller_google_protobuf_Empty);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Portkey.Contracts.CA.CaContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS12.Acs12Reflection.Descriptor.Services[0],
          global::Portkey.Contracts.CA.CaContractImplReflection.Descriptor.Services[0],
          global::Portkey.Contracts.CA.CaContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    /// <summary>Base class for the contract of CAContract</summary>
    // public abstract partial class CAContractBase : AElf.Sdk.CSharp.CSharpSmartContract<Portkey.Contracts.CA.CAContractState>
    // {
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty Initialize(global::Portkey.Contracts.CA.InitializeInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty CreateCAHolder(global::Portkey.Contracts.CA.CreateCAHolderInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty AddGuardian(global::Portkey.Contracts.CA.AddGuardianInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveGuardian(global::Portkey.Contracts.CA.RemoveGuardianInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateGuardian(global::Portkey.Contracts.CA.UpdateGuardianInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetGuardianForLogin(global::Portkey.Contracts.CA.SetGuardianForLoginInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty UnsetGuardianForLogin(global::Portkey.Contracts.CA.UnsetGuardianForLoginInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ManagerForwardCall(global::Portkey.Contracts.CA.ManagerForwardCallInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ManagerTransfer(global::Portkey.Contracts.CA.ManagerTransferInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ManagerTransferFrom(global::Portkey.Contracts.CA.ManagerTransferFromInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SocialRecovery(global::Portkey.Contracts.CA.SocialRecoveryInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty AddManagerInfo(global::Portkey.Contracts.CA.AddManagerInfoInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveManagerInfo(global::Portkey.Contracts.CA.RemoveManagerInfoInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveOtherManagerInfo(global::Portkey.Contracts.CA.RemoveOtherManagerInfoInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateManagerInfos(global::Portkey.Contracts.CA.UpdateManagerInfosInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty AddVerifierServerEndPoints(global::Portkey.Contracts.CA.AddVerifierServerEndPointsInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveVerifierServerEndPoints(global::Portkey.Contracts.CA.RemoveVerifierServerEndPointsInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveVerifierServer(global::Portkey.Contracts.CA.RemoveVerifierServerInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty AddCAServer(global::Portkey.Contracts.CA.AddCAServerInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveCAServer(global::Portkey.Contracts.CA.RemoveCAServerInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Portkey.Contracts.CA.GetHolderInfoOutput GetHolderInfo(global::Portkey.Contracts.CA.GetHolderInfoInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Portkey.Contracts.CA.GetVerifierServersOutput GetVerifierServers(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Portkey.Contracts.CA.GetCAServersOutput GetCAServers(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ValidateCAHolderInfoWithManagerInfosExists(global::Portkey.Contracts.CA.ValidateCAHolderInfoWithManagerInfosExistsInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SyncHolderInfo(global::Portkey.Contracts.CA.SyncHolderInfoInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Portkey.Contracts.CA.ValidateStrategyOutput ValidateStrategy(global::Portkey.Contracts.CA.ValidateStrategyInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetContractDelegationFee(global::Portkey.Contracts.CA.SetContractDelegationFeeInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Portkey.Contracts.CA.GetContractDelegationFeeOutput GetContractDelegationFee(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty AddCreatorController(global::Portkey.Contracts.CA.ControllerInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveCreatorController(global::Portkey.Contracts.CA.ControllerInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Portkey.Contracts.CA.ControllerOutput GetCreatorControllers(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty AddServerController(global::Portkey.Contracts.CA.ControllerInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveServerController(global::Portkey.Contracts.CA.ControllerInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Portkey.Contracts.CA.ControllerOutput GetServerControllers(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ChangeAdmin(global::Portkey.Contracts.CA.AdminInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Portkey.Contracts.CA.AdminOutput GetAdmin(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ChangeOperationTypeInSignatureEnabled(global::Portkey.Contracts.CA.OperationTypeInSignatureEnabledInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetCAContractAddresses(global::Portkey.Contracts.CA.SetCAContractAddressesInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty AddVerifierIdMapper(global::Portkey.Contracts.CA.AddVerifierIdMapperInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ManagerApprove(global::Portkey.Contracts.CA.ManagerApproveInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetTransferLimit(global::Portkey.Contracts.CA.SetTransferLimitInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Portkey.Contracts.CA.GetTransferLimitOutput GetTransferLimit(global::Portkey.Contracts.CA.GetTransferLimitInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetDefaultTokenTransferLimit(global::Portkey.Contracts.CA.SetDefaultTokenTransferLimitInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitOutput GetDefaultTokenTransferLimit(global::Portkey.Contracts.CA.GetDefaultTokenTransferLimitInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetForbiddenForwardCallContractMethod(global::Portkey.Contracts.CA.SetForbiddenForwardCallContractMethodInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ChangeManagerApproveForbiddenEnabled(global::Portkey.Contracts.CA.ManagerApproveForbiddenEnabledInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    // }
    //
    // public static aelf::ServerServiceDefinition BindService(CAContractBase serviceImpl)
    // {
    //   return aelf::ServerServiceDefinition.CreateBuilder()
    //       .AddDescriptors(Descriptors)
    //       .AddMethod(__Method_Initialize, serviceImpl.Initialize)
    //       .AddMethod(__Method_CreateCAHolder, serviceImpl.CreateCAHolder)
    //       .AddMethod(__Method_AddGuardian, serviceImpl.AddGuardian)
    //       .AddMethod(__Method_RemoveGuardian, serviceImpl.RemoveGuardian)
    //       .AddMethod(__Method_UpdateGuardian, serviceImpl.UpdateGuardian)
    //       .AddMethod(__Method_SetGuardianForLogin, serviceImpl.SetGuardianForLogin)
    //       .AddMethod(__Method_UnsetGuardianForLogin, serviceImpl.UnsetGuardianForLogin)
    //       .AddMethod(__Method_ManagerForwardCall, serviceImpl.ManagerForwardCall)
    //       .AddMethod(__Method_ManagerTransfer, serviceImpl.ManagerTransfer)
    //       .AddMethod(__Method_ManagerTransferFrom, serviceImpl.ManagerTransferFrom)
    //       .AddMethod(__Method_SocialRecovery, serviceImpl.SocialRecovery)
    //       .AddMethod(__Method_AddManagerInfo, serviceImpl.AddManagerInfo)
    //       .AddMethod(__Method_RemoveManagerInfo, serviceImpl.RemoveManagerInfo)
    //       .AddMethod(__Method_RemoveOtherManagerInfo, serviceImpl.RemoveOtherManagerInfo)
    //       .AddMethod(__Method_UpdateManagerInfos, serviceImpl.UpdateManagerInfos)
    //       .AddMethod(__Method_AddVerifierServerEndPoints, serviceImpl.AddVerifierServerEndPoints)
    //       .AddMethod(__Method_RemoveVerifierServerEndPoints, serviceImpl.RemoveVerifierServerEndPoints)
    //       .AddMethod(__Method_RemoveVerifierServer, serviceImpl.RemoveVerifierServer)
    //       .AddMethod(__Method_AddCAServer, serviceImpl.AddCAServer)
    //       .AddMethod(__Method_RemoveCAServer, serviceImpl.RemoveCAServer)
    //       .AddMethod(__Method_GetHolderInfo, serviceImpl.GetHolderInfo)
    //       .AddMethod(__Method_GetVerifierServers, serviceImpl.GetVerifierServers)
    //       .AddMethod(__Method_GetCAServers, serviceImpl.GetCAServers)
    //       .AddMethod(__Method_ValidateCAHolderInfoWithManagerInfosExists, serviceImpl.ValidateCAHolderInfoWithManagerInfosExists)
    //       .AddMethod(__Method_SyncHolderInfo, serviceImpl.SyncHolderInfo)
    //       .AddMethod(__Method_ValidateStrategy, serviceImpl.ValidateStrategy)
    //       .AddMethod(__Method_SetContractDelegationFee, serviceImpl.SetContractDelegationFee)
    //       .AddMethod(__Method_GetContractDelegationFee, serviceImpl.GetContractDelegationFee)
    //       .AddMethod(__Method_AddCreatorController, serviceImpl.AddCreatorController)
    //       .AddMethod(__Method_RemoveCreatorController, serviceImpl.RemoveCreatorController)
    //       .AddMethod(__Method_GetCreatorControllers, serviceImpl.GetCreatorControllers)
    //       .AddMethod(__Method_AddServerController, serviceImpl.AddServerController)
    //       .AddMethod(__Method_RemoveServerController, serviceImpl.RemoveServerController)
    //       .AddMethod(__Method_GetServerControllers, serviceImpl.GetServerControllers)
    //       .AddMethod(__Method_ChangeAdmin, serviceImpl.ChangeAdmin)
    //       .AddMethod(__Method_GetAdmin, serviceImpl.GetAdmin)
    //       .AddMethod(__Method_ChangeOperationTypeInSignatureEnabled, serviceImpl.ChangeOperationTypeInSignatureEnabled)
    //       .AddMethod(__Method_SetCAContractAddresses, serviceImpl.SetCAContractAddresses)
    //       .AddMethod(__Method_AddVerifierIdMapper, serviceImpl.AddVerifierIdMapper)
    //       .AddMethod(__Method_ManagerApprove, serviceImpl.ManagerApprove)
    //       .AddMethod(__Method_SetTransferLimit, serviceImpl.SetTransferLimit)
    //       .AddMethod(__Method_GetTransferLimit, serviceImpl.GetTransferLimit)
    //       .AddMethod(__Method_SetDefaultTokenTransferLimit, serviceImpl.SetDefaultTokenTransferLimit)
    //       .AddMethod(__Method_GetDefaultTokenTransferLimit, serviceImpl.GetDefaultTokenTransferLimit)
    //       .AddMethod(__Method_SetForbiddenForwardCallContractMethod, serviceImpl.SetForbiddenForwardCallContractMethod)
    //       .AddMethod(__Method_ChangeManagerApproveForbiddenEnabled, serviceImpl.ChangeManagerApproveForbiddenEnabled).Build();
    // }

  }
}
#endregion

