// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: oracle_common_message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oracle {

  /// <summary>Holder for reflection information generated from oracle_common_message.proto</summary>
  public static partial class OracleCommonMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for oracle_common_message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OracleCommonMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtvcmFjbGVfY29tbW9uX21lc3NhZ2UucHJvdG8SBm9yYWNsZRoPYWVsZi9j",
            "b3JlLnByb3RvGhJhZWxmL29wdGlvbnMucHJvdG8aC2FjczEyLnByb3RvGhtn",
            "b29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aHmdvb2dsZS9wcm90b2J1Zi93",
            "cmFwcGVycy5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90",
            "byLyAQoKQ29tbWl0bWVudBIeCgpyZXF1ZXN0X2lkGAEgASgLMgouYWVsZi5I",
            "YXNoEiIKC2Nvb3JkaW5hdG9yGAIgASgLMg0uYWVsZi5BZGRyZXNzEh0KBmNs",
            "aWVudBgDIAEoCzINLmFlbGYuQWRkcmVzcxIXCg9zdWJzY3JpcHRpb25faWQY",
            "BCABKAMSNQoRdGltZW91dF90aW1lc3RhbXAYBSABKAsyGi5nb29nbGUucHJv",
            "dG9idWYuVGltZXN0YW1wEhUKDXNwZWNpZmljX2RhdGEYBiABKAwSGgoScmVx",
            "dWVzdF90eXBlX2luZGV4GAcgASgFIl4KBlJlcG9ydBIOCgZyZXN1bHQYASAB",
            "KAwSDQoFZXJyb3IYAiABKAwSGQoRb25fY2hhaW5fbWV0YWRhdGEYAyABKAwS",
            "GgoSb2ZmX2NoYWluX21ldGFkYXRhGAQgASgMYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.Types.CoreReflection.Descriptor, global::AElf.OptionsReflection.Descriptor, global::AElf.Standards.ACS12.Acs12Reflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oracle.Commitment), global::Oracle.Commitment.Parser, new[]{ "RequestId", "Coordinator", "Client", "SubscriptionId", "TimeoutTimestamp", "SpecificData", "RequestTypeIndex" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Oracle.Report), global::Oracle.Report.Parser, new[]{ "Result", "Error", "OnChainMetadata", "OffChainMetadata" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Commitment : pb::IMessage<Commitment>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Commitment> _parser = new pb::MessageParser<Commitment>(() => new Commitment());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Commitment> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oracle.OracleCommonMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Commitment() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Commitment(Commitment other) : this() {
      requestId_ = other.requestId_ != null ? other.requestId_.Clone() : null;
      coordinator_ = other.coordinator_ != null ? other.coordinator_.Clone() : null;
      client_ = other.client_ != null ? other.client_.Clone() : null;
      subscriptionId_ = other.subscriptionId_;
      timeoutTimestamp_ = other.timeoutTimestamp_ != null ? other.timeoutTimestamp_.Clone() : null;
      specificData_ = other.specificData_;
      requestTypeIndex_ = other.requestTypeIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Commitment Clone() {
      return new Commitment(this);
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 1;
    private global::AElf.Types.Hash requestId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Hash RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    /// <summary>Field number for the "coordinator" field.</summary>
    public const int CoordinatorFieldNumber = 2;
    private global::AElf.Types.Address coordinator_;
    /// <summary>
    /// coordinator contract address
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address Coordinator {
      get { return coordinator_; }
      set {
        coordinator_ = value;
      }
    }

    /// <summary>Field number for the "client" field.</summary>
    public const int ClientFieldNumber = 3;
    private global::AElf.Types.Address client_;
    /// <summary>
    /// consumer contract address
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address Client {
      get { return client_; }
      set {
        client_ = value;
      }
    }

    /// <summary>Field number for the "subscription_id" field.</summary>
    public const int SubscriptionIdFieldNumber = 4;
    private long subscriptionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SubscriptionId {
      get { return subscriptionId_; }
      set {
        subscriptionId_ = value;
      }
    }

    /// <summary>Field number for the "timeout_timestamp" field.</summary>
    public const int TimeoutTimestampFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timeoutTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimeoutTimestamp {
      get { return timeoutTimestamp_; }
      set {
        timeoutTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "specific_data" field.</summary>
    public const int SpecificDataFieldNumber = 6;
    private pb::ByteString specificData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString SpecificData {
      get { return specificData_; }
      set {
        specificData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "request_type_index" field.</summary>
    public const int RequestTypeIndexFieldNumber = 7;
    private int requestTypeIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RequestTypeIndex {
      get { return requestTypeIndex_; }
      set {
        requestTypeIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Commitment);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Commitment other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(RequestId, other.RequestId)) return false;
      if (!object.Equals(Coordinator, other.Coordinator)) return false;
      if (!object.Equals(Client, other.Client)) return false;
      if (SubscriptionId != other.SubscriptionId) return false;
      if (!object.Equals(TimeoutTimestamp, other.TimeoutTimestamp)) return false;
      if (SpecificData != other.SpecificData) return false;
      if (RequestTypeIndex != other.RequestTypeIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (requestId_ != null) hash ^= RequestId.GetHashCode();
      if (coordinator_ != null) hash ^= Coordinator.GetHashCode();
      if (client_ != null) hash ^= Client.GetHashCode();
      if (SubscriptionId != 0L) hash ^= SubscriptionId.GetHashCode();
      if (timeoutTimestamp_ != null) hash ^= TimeoutTimestamp.GetHashCode();
      if (SpecificData.Length != 0) hash ^= SpecificData.GetHashCode();
      if (RequestTypeIndex != 0) hash ^= RequestTypeIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (requestId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(RequestId);
      }
      if (coordinator_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Coordinator);
      }
      if (client_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Client);
      }
      if (SubscriptionId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(SubscriptionId);
      }
      if (timeoutTimestamp_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(TimeoutTimestamp);
      }
      if (SpecificData.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(SpecificData);
      }
      if (RequestTypeIndex != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(RequestTypeIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (requestId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(RequestId);
      }
      if (coordinator_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Coordinator);
      }
      if (client_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Client);
      }
      if (SubscriptionId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(SubscriptionId);
      }
      if (timeoutTimestamp_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(TimeoutTimestamp);
      }
      if (SpecificData.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(SpecificData);
      }
      if (RequestTypeIndex != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(RequestTypeIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (requestId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RequestId);
      }
      if (coordinator_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Coordinator);
      }
      if (client_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Client);
      }
      if (SubscriptionId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SubscriptionId);
      }
      if (timeoutTimestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeoutTimestamp);
      }
      if (SpecificData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SpecificData);
      }
      if (RequestTypeIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RequestTypeIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Commitment other) {
      if (other == null) {
        return;
      }
      if (other.requestId_ != null) {
        if (requestId_ == null) {
          RequestId = new global::AElf.Types.Hash();
        }
        RequestId.MergeFrom(other.RequestId);
      }
      if (other.coordinator_ != null) {
        if (coordinator_ == null) {
          Coordinator = new global::AElf.Types.Address();
        }
        Coordinator.MergeFrom(other.Coordinator);
      }
      if (other.client_ != null) {
        if (client_ == null) {
          Client = new global::AElf.Types.Address();
        }
        Client.MergeFrom(other.Client);
      }
      if (other.SubscriptionId != 0L) {
        SubscriptionId = other.SubscriptionId;
      }
      if (other.timeoutTimestamp_ != null) {
        if (timeoutTimestamp_ == null) {
          TimeoutTimestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimeoutTimestamp.MergeFrom(other.TimeoutTimestamp);
      }
      if (other.SpecificData.Length != 0) {
        SpecificData = other.SpecificData;
      }
      if (other.RequestTypeIndex != 0) {
        RequestTypeIndex = other.RequestTypeIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (requestId_ == null) {
              RequestId = new global::AElf.Types.Hash();
            }
            input.ReadMessage(RequestId);
            break;
          }
          case 18: {
            if (coordinator_ == null) {
              Coordinator = new global::AElf.Types.Address();
            }
            input.ReadMessage(Coordinator);
            break;
          }
          case 26: {
            if (client_ == null) {
              Client = new global::AElf.Types.Address();
            }
            input.ReadMessage(Client);
            break;
          }
          case 32: {
            SubscriptionId = input.ReadInt64();
            break;
          }
          case 42: {
            if (timeoutTimestamp_ == null) {
              TimeoutTimestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeoutTimestamp);
            break;
          }
          case 50: {
            SpecificData = input.ReadBytes();
            break;
          }
          case 56: {
            RequestTypeIndex = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (requestId_ == null) {
              RequestId = new global::AElf.Types.Hash();
            }
            input.ReadMessage(RequestId);
            break;
          }
          case 18: {
            if (coordinator_ == null) {
              Coordinator = new global::AElf.Types.Address();
            }
            input.ReadMessage(Coordinator);
            break;
          }
          case 26: {
            if (client_ == null) {
              Client = new global::AElf.Types.Address();
            }
            input.ReadMessage(Client);
            break;
          }
          case 32: {
            SubscriptionId = input.ReadInt64();
            break;
          }
          case 42: {
            if (timeoutTimestamp_ == null) {
              TimeoutTimestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeoutTimestamp);
            break;
          }
          case 50: {
            SpecificData = input.ReadBytes();
            break;
          }
          case 56: {
            RequestTypeIndex = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Report : pb::IMessage<Report>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Report> _parser = new pb::MessageParser<Report>(() => new Report());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Report> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oracle.OracleCommonMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Report() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Report(Report other) : this() {
      result_ = other.result_;
      error_ = other.error_;
      onChainMetadata_ = other.onChainMetadata_;
      offChainMetadata_ = other.offChainMetadata_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Report Clone() {
      return new Report(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private pb::ByteString result_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Result {
      get { return result_; }
      set {
        result_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private pb::ByteString error_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "on_chain_metadata" field.</summary>
    public const int OnChainMetadataFieldNumber = 3;
    private pb::ByteString onChainMetadata_ = pb::ByteString.Empty;
    /// <summary>
    /// serialized Commitment
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString OnChainMetadata {
      get { return onChainMetadata_; }
      set {
        onChainMetadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "off_chain_metadata" field.</summary>
    public const int OffChainMetadataFieldNumber = 4;
    private pb::ByteString offChainMetadata_ = pb::ByteString.Empty;
    /// <summary>
    /// TODO use in getDonFee() for dynamic billing
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString OffChainMetadata {
      get { return offChainMetadata_; }
      set {
        offChainMetadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Report);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Report other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (Error != other.Error) return false;
      if (OnChainMetadata != other.OnChainMetadata) return false;
      if (OffChainMetadata != other.OffChainMetadata) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result.Length != 0) hash ^= Result.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (OnChainMetadata.Length != 0) hash ^= OnChainMetadata.GetHashCode();
      if (OffChainMetadata.Length != 0) hash ^= OffChainMetadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Result);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Error);
      }
      if (OnChainMetadata.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(OnChainMetadata);
      }
      if (OffChainMetadata.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(OffChainMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Result);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Error);
      }
      if (OnChainMetadata.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(OnChainMetadata);
      }
      if (OffChainMetadata.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(OffChainMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Result);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Error);
      }
      if (OnChainMetadata.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(OnChainMetadata);
      }
      if (OffChainMetadata.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(OffChainMetadata);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Report other) {
      if (other == null) {
        return;
      }
      if (other.Result.Length != 0) {
        Result = other.Result;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.OnChainMetadata.Length != 0) {
        OnChainMetadata = other.OnChainMetadata;
      }
      if (other.OffChainMetadata.Length != 0) {
        OffChainMetadata = other.OffChainMetadata;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Result = input.ReadBytes();
            break;
          }
          case 18: {
            Error = input.ReadBytes();
            break;
          }
          case 26: {
            OnChainMetadata = input.ReadBytes();
            break;
          }
          case 34: {
            OffChainMetadata = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Result = input.ReadBytes();
            break;
          }
          case 18: {
            Error = input.ReadBytes();
            break;
          }
          case 26: {
            OnChainMetadata = input.ReadBytes();
            break;
          }
          case 34: {
            OffChainMetadata = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
