// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: token_contract_impl.proto
// </auto-generated>
// Original file comments:
// *
// MultiToken contract.
//
// The MultiToken contract is mainly used to manage the user's account and transaction fees related Settings.
// 
// Implement AElf Standards ACS1 and ACS2.
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.MultiToken {

  #region Events
  public partial class TransactionFeeDelegateInfoAdded : aelf::IEvent<TransactionFeeDelegateInfoAdded>
  {
    public global::System.Collections.Generic.IEnumerable<TransactionFeeDelegateInfoAdded> GetIndexed()
    {
      return new List<TransactionFeeDelegateInfoAdded>
      {
      };
    }

    public TransactionFeeDelegateInfoAdded GetNonIndexed()
    {
      return new TransactionFeeDelegateInfoAdded
      {
        Delegator = Delegator,
        Delegatee = Delegatee,
        Caller = Caller,
        DelegateTransactionList = DelegateTransactionList,
      };
    }
  }

  public partial class TransactionFeeDelegateInfoUpdated : aelf::IEvent<TransactionFeeDelegateInfoUpdated>
  {
    public global::System.Collections.Generic.IEnumerable<TransactionFeeDelegateInfoUpdated> GetIndexed()
    {
      return new List<TransactionFeeDelegateInfoUpdated>
      {
      };
    }

    public TransactionFeeDelegateInfoUpdated GetNonIndexed()
    {
      return new TransactionFeeDelegateInfoUpdated
      {
        Delegator = Delegator,
        Delegatee = Delegatee,
        Caller = Caller,
        DelegateTransactionList = DelegateTransactionList,
      };
    }
  }

  public partial class TransactionFeeDelegateInfoCancelled : aelf::IEvent<TransactionFeeDelegateInfoCancelled>
  {
    public global::System.Collections.Generic.IEnumerable<TransactionFeeDelegateInfoCancelled> GetIndexed()
    {
      return new List<TransactionFeeDelegateInfoCancelled>
      {
      };
    }

    public TransactionFeeDelegateInfoCancelled GetNonIndexed()
    {
      return new TransactionFeeDelegateInfoCancelled
      {
        Delegator = Delegator,
        Delegatee = Delegatee,
        Caller = Caller,
        DelegateTransactionList = DelegateTransactionList,
      };
    }
  }

  #endregion
  public static partial class TokenContractImplContainer
  {
    static readonly string __ServiceName = "tokenimpl.TokenContractImpl";

    #region Marshallers
    static readonly aelf::Marshaller<global::AElf.Standards.ACS1.MethodFees> __Marshaller_acs1_MethodFees = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Standards.ACS1.MethodFees.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AuthorityInfo> __Marshaller_AuthorityInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AuthorityInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Transaction> __Marshaller_aelf_Transaction = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Transaction.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Standards.ACS2.ResourceInfo> __Marshaller_acs2_ResourceInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Standards.ACS2.ResourceInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.CreateInput> __Marshaller_token_CreateInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.CreateInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.IssueInput> __Marshaller_token_IssueInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.IssueInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.TransferInput> __Marshaller_token_TransferInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.TransferInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.TransferFromInput> __Marshaller_token_TransferFromInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.TransferFromInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.ApproveInput> __Marshaller_token_ApproveInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.ApproveInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.BatchApproveInput> __Marshaller_token_BatchApproveInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.BatchApproveInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.UnApproveInput> __Marshaller_token_UnApproveInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.UnApproveInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.LockInput> __Marshaller_token_LockInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.LockInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.UnlockInput> __Marshaller_token_UnlockInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.UnlockInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.BurnInput> __Marshaller_token_BurnInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.BurnInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.SetPrimaryTokenSymbolInput> __Marshaller_token_SetPrimaryTokenSymbolInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.SetPrimaryTokenSymbolInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.CrossChainTransferInput> __Marshaller_token_CrossChainTransferInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.CrossChainTransferInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.CrossChainReceiveTokenInput> __Marshaller_token_CrossChainReceiveTokenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.CrossChainReceiveTokenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.CrossChainCreateTokenInput> __Marshaller_token_CrossChainCreateTokenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.CrossChainCreateTokenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.InitializeFromParentChainInput> __Marshaller_token_InitializeFromParentChainInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.InitializeFromParentChainInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.TotalTransactionFeesMap> __Marshaller_token_TotalTransactionFeesMap = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.TotalTransactionFeesMap.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.ChargeTransactionFeesInput> __Marshaller_token_ChargeTransactionFeesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.ChargeTransactionFeesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.ChargeTransactionFeesOutput> __Marshaller_token_ChargeTransactionFeesOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.ChargeTransactionFeesOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.CheckThresholdInput> __Marshaller_token_CheckThresholdInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.CheckThresholdInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.TotalResourceTokensMaps> __Marshaller_token_TotalResourceTokensMaps = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.TotalResourceTokensMaps.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.ChargeResourceTokenInput> __Marshaller_token_ChargeResourceTokenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.ChargeResourceTokenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.SymbolListToPayTxSizeFee> __Marshaller_token_SymbolListToPayTxSizeFee = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.SymbolListToPayTxSizeFee.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.UpdateCoefficientsInput> __Marshaller_token_UpdateCoefficientsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.UpdateCoefficientsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.SetTransactionFeeDelegationsInput> __Marshaller_token_SetTransactionFeeDelegationsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.SetTransactionFeeDelegationsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.SetTransactionFeeDelegationsOutput> __Marshaller_token_SetTransactionFeeDelegationsOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.SetTransactionFeeDelegationsOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegatorInput> __Marshaller_token_RemoveTransactionFeeDelegatorInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegatorInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegateeInput> __Marshaller_token_RemoveTransactionFeeDelegateeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegateeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.SetSymbolAliasInput> __Marshaller_token_SetSymbolAliasInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.SetSymbolAliasInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateesInput> __Marshaller_token_GetTransactionFeeDelegateesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateesOutput> __Marshaller_token_GetTransactionFeeDelegateesOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateesOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetTokenInfoInput> __Marshaller_token_GetTokenInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetTokenInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.TokenInfo> __Marshaller_token_TokenInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.TokenInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.TokenInfoList> __Marshaller_token_TokenInfoList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.TokenInfoList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetBalanceInput> __Marshaller_token_GetBalanceInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetBalanceInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetBalanceOutput> __Marshaller_token_GetBalanceOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetBalanceOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetAllowanceInput> __Marshaller_token_GetAllowanceInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetAllowanceInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetAllowanceOutput> __Marshaller_token_GetAllowanceOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetAllowanceOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.IsInWhiteListInput> __Marshaller_token_IsInWhiteListInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.IsInWhiteListInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetLockedAmountInput> __Marshaller_token_GetLockedAmountInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetLockedAmountInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetLockedAmountOutput> __Marshaller_token_GetLockedAmountOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetLockedAmountOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetCrossChainTransferTokenContractAddressInput> __Marshaller_token_GetCrossChainTransferTokenContractAddressInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetCrossChainTransferTokenContractAddressInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.CalculateFeeCoefficients> __Marshaller_token_CalculateFeeCoefficients = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.CalculateFeeCoefficients.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.StringList> __Marshaller_token_StringList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.StringList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegationsOfADelegateeInput> __Marshaller_token_GetTransactionFeeDelegationsOfADelegateeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetTransactionFeeDelegationsOfADelegateeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.TransactionFeeDelegations> __Marshaller_token_TransactionFeeDelegations = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.TransactionFeeDelegations.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.AdvanceResourceTokenInput> __Marshaller_tokenimpl_AdvanceResourceTokenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.AdvanceResourceTokenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.TakeResourceTokenBackInput> __Marshaller_tokenimpl_TakeResourceTokenBackInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.TakeResourceTokenBackInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.RegisterCrossChainTokenContractAddressInput> __Marshaller_tokenimpl_RegisterCrossChainTokenContractAddressInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.RegisterCrossChainTokenContractAddressInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.ValidateTokenInfoExistsInput> __Marshaller_tokenimpl_ValidateTokenInfoExistsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.ValidateTokenInfoExistsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.UpdateRentalInput> __Marshaller_tokenimpl_UpdateRentalInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.UpdateRentalInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.UpdateRentedResourcesInput> __Marshaller_tokenimpl_UpdateRentedResourcesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.UpdateRentedResourcesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.TransferToContractInput> __Marshaller_tokenimpl_TransferToContractInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.TransferToContractInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.ConfigTransactionFeeFreeAllowancesInput> __Marshaller_tokenimpl_ConfigTransactionFeeFreeAllowancesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.ConfigTransactionFeeFreeAllowancesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.RemoveTransactionFeeFreeAllowancesConfigInput> __Marshaller_tokenimpl_RemoveTransactionFeeFreeAllowancesConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.RemoveTransactionFeeFreeAllowancesConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.SetTransactionFeeDelegateInfosInput> __Marshaller_tokenimpl_SetTransactionFeeDelegateInfosInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.SetTransactionFeeDelegateInfosInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegatorInfosInput> __Marshaller_tokenimpl_RemoveTransactionFeeDelegatorInfosInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegatorInfosInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegateeInfosInput> __Marshaller_tokenimpl_RemoveTransactionFeeDelegateeInfosInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegateeInfosInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.ResourceUsage> __Marshaller_tokenimpl_ResourceUsage = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.ResourceUsage.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.UserFeeController> __Marshaller_tokenimpl_UserFeeController = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.UserFeeController.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.DeveloperFeeController> __Marshaller_tokenimpl_DeveloperFeeController = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.DeveloperFeeController.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetVirtualAddressForLockingInput> __Marshaller_tokenimpl_GetVirtualAddressForLockingInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetVirtualAddressForLockingInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.OwningRental> __Marshaller_tokenimpl_OwningRental = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.OwningRental.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.OwningRentalUnitValue> __Marshaller_tokenimpl_OwningRentalUnitValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.OwningRentalUnitValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.TransactionFeeFreeAllowancesMap> __Marshaller_tokenimpl_TransactionFeeFreeAllowancesMap = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.TransactionFeeFreeAllowancesMap.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetTransactionFeeFreeAllowancesConfigOutput> __Marshaller_tokenimpl_GetTransactionFeeFreeAllowancesConfigOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetTransactionFeeFreeAllowancesConfigOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateeListInput> __Marshaller_tokenimpl_GetTransactionFeeDelegateeListInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateeListInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateeListOutput> __Marshaller_tokenimpl_GetTransactionFeeDelegateeListOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateeListOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateInfoInput> __Marshaller_tokenimpl_GetTransactionFeeDelegateInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.ModifyTokenIssuerAndOwnerInput> __Marshaller_tokenimpl_ModifyTokenIssuerAndOwnerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.ModifyTokenIssuerAndOwnerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MultiToken.SetTokenIssuerAndOwnerModificationEnabledInput> __Marshaller_tokenimpl_SetTokenIssuerAndOwnerModificationEnabledInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MultiToken.SetTokenIssuerAndOwnerModificationEnabledInput.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AElf.Standards.ACS1.MethodFees, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMethodFee = new aelf::Method<global::AElf.Standards.ACS1.MethodFees, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMethodFee",
        __Marshaller_acs1_MethodFees,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeMethodFeeController = new aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeMethodFeeController",
        __Marshaller_AuthorityInfo,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Standards.ACS1.MethodFees> __Method_GetMethodFee = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Standards.ACS1.MethodFees>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMethodFee",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_acs1_MethodFees);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo> __Method_GetMethodFeeController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMethodFeeController",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AuthorityInfo);

    static readonly aelf::Method<global::AElf.Types.Transaction, global::AElf.Standards.ACS2.ResourceInfo> __Method_GetResourceInfo = new aelf::Method<global::AElf.Types.Transaction, global::AElf.Standards.ACS2.ResourceInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetResourceInfo",
        __Marshaller_aelf_Transaction,
        __Marshaller_acs2_ResourceInfo);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.CreateInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Create = new aelf::Method<global::AElf.Contracts.MultiToken.CreateInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Create",
        __Marshaller_token_CreateInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.IssueInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Issue = new aelf::Method<global::AElf.Contracts.MultiToken.IssueInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Issue",
        __Marshaller_token_IssueInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.TransferInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Transfer = new aelf::Method<global::AElf.Contracts.MultiToken.TransferInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Transfer",
        __Marshaller_token_TransferInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.TransferFromInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TransferFrom = new aelf::Method<global::AElf.Contracts.MultiToken.TransferFromInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "TransferFrom",
        __Marshaller_token_TransferFromInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.ApproveInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Approve = new aelf::Method<global::AElf.Contracts.MultiToken.ApproveInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Approve",
        __Marshaller_token_ApproveInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.BatchApproveInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_BatchApprove = new aelf::Method<global::AElf.Contracts.MultiToken.BatchApproveInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "BatchApprove",
        __Marshaller_token_BatchApproveInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.UnApproveInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UnApprove = new aelf::Method<global::AElf.Contracts.MultiToken.UnApproveInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UnApprove",
        __Marshaller_token_UnApproveInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.LockInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Lock = new aelf::Method<global::AElf.Contracts.MultiToken.LockInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Lock",
        __Marshaller_token_LockInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.UnlockInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Unlock = new aelf::Method<global::AElf.Contracts.MultiToken.UnlockInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Unlock",
        __Marshaller_token_UnlockInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.BurnInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Burn = new aelf::Method<global::AElf.Contracts.MultiToken.BurnInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Burn",
        __Marshaller_token_BurnInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.SetPrimaryTokenSymbolInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPrimaryTokenSymbol = new aelf::Method<global::AElf.Contracts.MultiToken.SetPrimaryTokenSymbolInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPrimaryTokenSymbol",
        __Marshaller_token_SetPrimaryTokenSymbolInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.CrossChainTransferInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CrossChainTransfer = new aelf::Method<global::AElf.Contracts.MultiToken.CrossChainTransferInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CrossChainTransfer",
        __Marshaller_token_CrossChainTransferInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.CrossChainReceiveTokenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CrossChainReceiveToken = new aelf::Method<global::AElf.Contracts.MultiToken.CrossChainReceiveTokenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CrossChainReceiveToken",
        __Marshaller_token_CrossChainReceiveTokenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.CrossChainCreateTokenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CrossChainCreateToken = new aelf::Method<global::AElf.Contracts.MultiToken.CrossChainCreateTokenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CrossChainCreateToken",
        __Marshaller_token_CrossChainCreateTokenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.InitializeFromParentChainInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InitializeFromParentChain = new aelf::Method<global::AElf.Contracts.MultiToken.InitializeFromParentChainInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "InitializeFromParentChain",
        __Marshaller_token_InitializeFromParentChainInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.TotalTransactionFeesMap, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ClaimTransactionFees = new aelf::Method<global::AElf.Contracts.MultiToken.TotalTransactionFeesMap, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ClaimTransactionFees",
        __Marshaller_token_TotalTransactionFeesMap,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.ChargeTransactionFeesInput, global::AElf.Contracts.MultiToken.ChargeTransactionFeesOutput> __Method_ChargeTransactionFees = new aelf::Method<global::AElf.Contracts.MultiToken.ChargeTransactionFeesInput, global::AElf.Contracts.MultiToken.ChargeTransactionFeesOutput>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChargeTransactionFees",
        __Marshaller_token_ChargeTransactionFeesInput,
        __Marshaller_token_ChargeTransactionFeesOutput);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.ChargeTransactionFeesInput, global::AElf.Contracts.MultiToken.ChargeTransactionFeesOutput> __Method_ChargeUserContractTransactionFees = new aelf::Method<global::AElf.Contracts.MultiToken.ChargeTransactionFeesInput, global::AElf.Contracts.MultiToken.ChargeTransactionFeesOutput>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChargeUserContractTransactionFees",
        __Marshaller_token_ChargeTransactionFeesInput,
        __Marshaller_token_ChargeTransactionFeesOutput);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.CheckThresholdInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CheckThreshold = new aelf::Method<global::AElf.Contracts.MultiToken.CheckThresholdInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CheckThreshold",
        __Marshaller_token_CheckThresholdInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InitialCoefficients = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "InitialCoefficients",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.TotalResourceTokensMaps, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DonateResourceToken = new aelf::Method<global::AElf.Contracts.MultiToken.TotalResourceTokensMaps, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "DonateResourceToken",
        __Marshaller_token_TotalResourceTokensMaps,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.ChargeResourceTokenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChargeResourceToken = new aelf::Method<global::AElf.Contracts.MultiToken.ChargeResourceTokenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChargeResourceToken",
        __Marshaller_token_ChargeResourceTokenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CheckResourceToken = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CheckResourceToken",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.SymbolListToPayTxSizeFee, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetSymbolsToPayTxSizeFee = new aelf::Method<global::AElf.Contracts.MultiToken.SymbolListToPayTxSizeFee, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetSymbolsToPayTxSizeFee",
        __Marshaller_token_SymbolListToPayTxSizeFee,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.UpdateCoefficientsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateCoefficientsForSender = new aelf::Method<global::AElf.Contracts.MultiToken.UpdateCoefficientsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdateCoefficientsForSender",
        __Marshaller_token_UpdateCoefficientsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.UpdateCoefficientsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateCoefficientsForContract = new aelf::Method<global::AElf.Contracts.MultiToken.UpdateCoefficientsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdateCoefficientsForContract",
        __Marshaller_token_UpdateCoefficientsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InitializeAuthorizedController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "InitializeAuthorizedController",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddAddressToCreateTokenWhiteList = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddAddressToCreateTokenWhiteList",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveAddressFromCreateTokenWhiteList = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveAddressFromCreateTokenWhiteList",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.SetTransactionFeeDelegationsInput, global::AElf.Contracts.MultiToken.SetTransactionFeeDelegationsOutput> __Method_SetTransactionFeeDelegations = new aelf::Method<global::AElf.Contracts.MultiToken.SetTransactionFeeDelegationsInput, global::AElf.Contracts.MultiToken.SetTransactionFeeDelegationsOutput>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetTransactionFeeDelegations",
        __Marshaller_token_SetTransactionFeeDelegationsInput,
        __Marshaller_token_SetTransactionFeeDelegationsOutput);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegatorInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveTransactionFeeDelegator = new aelf::Method<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegatorInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveTransactionFeeDelegator",
        __Marshaller_token_RemoveTransactionFeeDelegatorInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegateeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveTransactionFeeDelegatee = new aelf::Method<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegateeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveTransactionFeeDelegatee",
        __Marshaller_token_RemoveTransactionFeeDelegateeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.SetSymbolAliasInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetSymbolAlias = new aelf::Method<global::AElf.Contracts.MultiToken.SetSymbolAliasInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetSymbolAlias",
        __Marshaller_token_SetSymbolAliasInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateesInput, global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateesOutput> __Method_GetTransactionFeeDelegatees = new aelf::Method<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateesInput, global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateesOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransactionFeeDelegatees",
        __Marshaller_token_GetTransactionFeeDelegateesInput,
        __Marshaller_token_GetTransactionFeeDelegateesOutput);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetTokenInfoInput, global::AElf.Contracts.MultiToken.TokenInfo> __Method_GetTokenInfo = new aelf::Method<global::AElf.Contracts.MultiToken.GetTokenInfoInput, global::AElf.Contracts.MultiToken.TokenInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTokenInfo",
        __Marshaller_token_GetTokenInfoInput,
        __Marshaller_token_TokenInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.TokenInfo> __Method_GetNativeTokenInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.TokenInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetNativeTokenInfo",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_token_TokenInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.TokenInfoList> __Method_GetResourceTokenInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.TokenInfoList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetResourceTokenInfo",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_token_TokenInfoList);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetBalanceInput, global::AElf.Contracts.MultiToken.GetBalanceOutput> __Method_GetBalance = new aelf::Method<global::AElf.Contracts.MultiToken.GetBalanceInput, global::AElf.Contracts.MultiToken.GetBalanceOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetBalance",
        __Marshaller_token_GetBalanceInput,
        __Marshaller_token_GetBalanceOutput);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetAllowanceInput, global::AElf.Contracts.MultiToken.GetAllowanceOutput> __Method_GetAllowance = new aelf::Method<global::AElf.Contracts.MultiToken.GetAllowanceInput, global::AElf.Contracts.MultiToken.GetAllowanceOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAllowance",
        __Marshaller_token_GetAllowanceInput,
        __Marshaller_token_GetAllowanceOutput);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetAllowanceInput, global::AElf.Contracts.MultiToken.GetAllowanceOutput> __Method_GetAvailableAllowance = new aelf::Method<global::AElf.Contracts.MultiToken.GetAllowanceInput, global::AElf.Contracts.MultiToken.GetAllowanceOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAvailableAllowance",
        __Marshaller_token_GetAllowanceInput,
        __Marshaller_token_GetAllowanceOutput);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.IsInWhiteListInput, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_IsInWhiteList = new aelf::Method<global::AElf.Contracts.MultiToken.IsInWhiteListInput, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "IsInWhiteList",
        __Marshaller_token_IsInWhiteListInput,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetLockedAmountInput, global::AElf.Contracts.MultiToken.GetLockedAmountOutput> __Method_GetLockedAmount = new aelf::Method<global::AElf.Contracts.MultiToken.GetLockedAmountInput, global::AElf.Contracts.MultiToken.GetLockedAmountOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLockedAmount",
        __Marshaller_token_GetLockedAmountInput,
        __Marshaller_token_GetLockedAmountOutput);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetCrossChainTransferTokenContractAddressInput, global::AElf.Types.Address> __Method_GetCrossChainTransferTokenContractAddress = new aelf::Method<global::AElf.Contracts.MultiToken.GetCrossChainTransferTokenContractAddressInput, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCrossChainTransferTokenContractAddress",
        __Marshaller_token_GetCrossChainTransferTokenContractAddressInput,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetPrimaryTokenSymbol = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPrimaryTokenSymbol",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::AElf.Contracts.MultiToken.CalculateFeeCoefficients> __Method_GetCalculateFeeCoefficientsForContract = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::AElf.Contracts.MultiToken.CalculateFeeCoefficients>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCalculateFeeCoefficientsForContract",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_token_CalculateFeeCoefficients);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.CalculateFeeCoefficients> __Method_GetCalculateFeeCoefficientsForSender = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.CalculateFeeCoefficients>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCalculateFeeCoefficientsForSender",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_token_CalculateFeeCoefficients);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.SymbolListToPayTxSizeFee> __Method_GetSymbolsToPayTxSizeFee = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.SymbolListToPayTxSizeFee>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSymbolsToPayTxSizeFee",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_token_SymbolListToPayTxSizeFee);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Hash> __Method_GetLatestTotalTransactionFeesMapHash = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Hash>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLatestTotalTransactionFeesMapHash",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Hash);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Hash> __Method_GetLatestTotalResourceTokensMapsHash = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Hash>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLatestTotalResourceTokensMapsHash",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Hash);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_IsTokenAvailableForMethodFee = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "IsTokenAvailableForMethodFee",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.StringList> __Method_GetReservedExternalInfoKeyList = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.StringList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetReservedExternalInfoKeyList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_token_StringList);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegationsOfADelegateeInput, global::AElf.Contracts.MultiToken.TransactionFeeDelegations> __Method_GetTransactionFeeDelegationsOfADelegatee = new aelf::Method<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegationsOfADelegateeInput, global::AElf.Contracts.MultiToken.TransactionFeeDelegations>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransactionFeeDelegationsOfADelegatee",
        __Marshaller_token_GetTransactionFeeDelegationsOfADelegateeInput,
        __Marshaller_token_TransactionFeeDelegations);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetTokenAlias = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTokenAlias",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetSymbolByAlias = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSymbolByAlias",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.AdvanceResourceTokenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AdvanceResourceToken = new aelf::Method<global::AElf.Contracts.MultiToken.AdvanceResourceTokenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AdvanceResourceToken",
        __Marshaller_tokenimpl_AdvanceResourceTokenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.TakeResourceTokenBackInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TakeResourceTokenBack = new aelf::Method<global::AElf.Contracts.MultiToken.TakeResourceTokenBackInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "TakeResourceTokenBack",
        __Marshaller_tokenimpl_TakeResourceTokenBackInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.RegisterCrossChainTokenContractAddressInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RegisterCrossChainTokenContractAddress = new aelf::Method<global::AElf.Contracts.MultiToken.RegisterCrossChainTokenContractAddressInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RegisterCrossChainTokenContractAddress",
        __Marshaller_tokenimpl_RegisterCrossChainTokenContractAddressInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetFeeReceiver = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetFeeReceiver",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.ValidateTokenInfoExistsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ValidateTokenInfoExists = new aelf::Method<global::AElf.Contracts.MultiToken.ValidateTokenInfoExistsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ValidateTokenInfoExists",
        __Marshaller_tokenimpl_ValidateTokenInfoExistsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.UpdateRentalInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateRental = new aelf::Method<global::AElf.Contracts.MultiToken.UpdateRentalInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdateRental",
        __Marshaller_tokenimpl_UpdateRentalInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.UpdateRentedResourcesInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateRentedResources = new aelf::Method<global::AElf.Contracts.MultiToken.UpdateRentedResourcesInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdateRentedResources",
        __Marshaller_tokenimpl_UpdateRentedResourcesInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.TransferToContractInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TransferToContract = new aelf::Method<global::AElf.Contracts.MultiToken.TransferToContractInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "TransferToContract",
        __Marshaller_tokenimpl_TransferToContractInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeSideChainRentalController = new aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeSideChainRentalController",
        __Marshaller_AuthorityInfo,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeSymbolsToPayTXSizeFeeController = new aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeSymbolsToPayTXSizeFeeController",
        __Marshaller_AuthorityInfo,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeCrossChainTokenContractRegistrationController = new aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeCrossChainTokenContractRegistrationController",
        __Marshaller_AuthorityInfo,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeUserFeeController = new aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeUserFeeController",
        __Marshaller_AuthorityInfo,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeDeveloperController = new aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeDeveloperController",
        __Marshaller_AuthorityInfo,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.ConfigTransactionFeeFreeAllowancesInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ConfigTransactionFeeFreeAllowances = new aelf::Method<global::AElf.Contracts.MultiToken.ConfigTransactionFeeFreeAllowancesInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ConfigTransactionFeeFreeAllowances",
        __Marshaller_tokenimpl_ConfigTransactionFeeFreeAllowancesInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.RemoveTransactionFeeFreeAllowancesConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveTransactionFeeFreeAllowancesConfig = new aelf::Method<global::AElf.Contracts.MultiToken.RemoveTransactionFeeFreeAllowancesConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveTransactionFeeFreeAllowancesConfig",
        __Marshaller_tokenimpl_RemoveTransactionFeeFreeAllowancesConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMaxBatchApproveCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMaxBatchApproveCount",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.SetTransactionFeeDelegateInfosInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetTransactionFeeDelegateInfos = new aelf::Method<global::AElf.Contracts.MultiToken.SetTransactionFeeDelegateInfosInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetTransactionFeeDelegateInfos",
        __Marshaller_tokenimpl_SetTransactionFeeDelegateInfosInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegatorInfosInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveTransactionFeeDelegatorInfos = new aelf::Method<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegatorInfosInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveTransactionFeeDelegatorInfos",
        __Marshaller_tokenimpl_RemoveTransactionFeeDelegatorInfosInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegateeInfosInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveTransactionFeeDelegateeInfos = new aelf::Method<global::AElf.Contracts.MultiToken.RemoveTransactionFeeDelegateeInfosInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveTransactionFeeDelegateeInfos",
        __Marshaller_tokenimpl_RemoveTransactionFeeDelegateeInfosInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetFeeReceiver = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetFeeReceiver",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.ResourceUsage> __Method_GetResourceUsage = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.ResourceUsage>(
        aelf::MethodType.View,
        __ServiceName,
        "GetResourceUsage",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_tokenimpl_ResourceUsage);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo> __Method_GetSymbolsToPayTXSizeFeeController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSymbolsToPayTXSizeFeeController",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AuthorityInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo> __Method_GetCrossChainTokenContractRegistrationController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCrossChainTokenContractRegistrationController",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AuthorityInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.UserFeeController> __Method_GetUserFeeController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.UserFeeController>(
        aelf::MethodType.View,
        __ServiceName,
        "GetUserFeeController",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_tokenimpl_UserFeeController);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.DeveloperFeeController> __Method_GetDeveloperFeeController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.DeveloperFeeController>(
        aelf::MethodType.View,
        __ServiceName,
        "GetDeveloperFeeController",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_tokenimpl_DeveloperFeeController);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo> __Method_GetSideChainRentalControllerCreateInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSideChainRentalControllerCreateInfo",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AuthorityInfo);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetVirtualAddressForLockingInput, global::AElf.Types.Address> __Method_GetVirtualAddressForLocking = new aelf::Method<global::AElf.Contracts.MultiToken.GetVirtualAddressForLockingInput, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVirtualAddressForLocking",
        __Marshaller_tokenimpl_GetVirtualAddressForLockingInput,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.OwningRental> __Method_GetOwningRental = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.OwningRental>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOwningRental",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_tokenimpl_OwningRental);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.OwningRentalUnitValue> __Method_GetOwningRentalUnitValue = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.OwningRentalUnitValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOwningRentalUnitValue",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_tokenimpl_OwningRentalUnitValue);

    static readonly aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.MultiToken.TransactionFeeFreeAllowancesMap> __Method_GetTransactionFeeFreeAllowances = new aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.MultiToken.TransactionFeeFreeAllowancesMap>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransactionFeeFreeAllowances",
        __Marshaller_aelf_Address,
        __Marshaller_tokenimpl_TransactionFeeFreeAllowancesMap);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.GetTransactionFeeFreeAllowancesConfigOutput> __Method_GetTransactionFeeFreeAllowancesConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.MultiToken.GetTransactionFeeFreeAllowancesConfigOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransactionFeeFreeAllowancesConfig",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_tokenimpl_GetTransactionFeeFreeAllowancesConfigOutput);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateeListInput, global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateeListOutput> __Method_GetTransactionFeeDelegateeList = new aelf::Method<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateeListInput, global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateeListOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransactionFeeDelegateeList",
        __Marshaller_tokenimpl_GetTransactionFeeDelegateeListInput,
        __Marshaller_tokenimpl_GetTransactionFeeDelegateeListOutput);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateInfoInput, global::AElf.Contracts.MultiToken.TransactionFeeDelegations> __Method_GetTransactionFeeDelegateInfo = new aelf::Method<global::AElf.Contracts.MultiToken.GetTransactionFeeDelegateInfoInput, global::AElf.Contracts.MultiToken.TransactionFeeDelegations>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransactionFeeDelegateInfo",
        __Marshaller_tokenimpl_GetTransactionFeeDelegateInfoInput,
        __Marshaller_token_TransactionFeeDelegations);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.ModifyTokenIssuerAndOwnerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ModifyTokenIssuerAndOwner = new aelf::Method<global::AElf.Contracts.MultiToken.ModifyTokenIssuerAndOwnerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ModifyTokenIssuerAndOwner",
        __Marshaller_tokenimpl_ModifyTokenIssuerAndOwnerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MultiToken.SetTokenIssuerAndOwnerModificationEnabledInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetTokenIssuerAndOwnerModificationEnabled = new aelf::Method<global::AElf.Contracts.MultiToken.SetTokenIssuerAndOwnerModificationEnabledInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetTokenIssuerAndOwnerModificationEnabled",
        __Marshaller_tokenimpl_SetTokenIssuerAndOwnerModificationEnabledInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_GetTokenIssuerAndOwnerModificationEnabled = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTokenIssuerAndOwnerModificationEnabled",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetMaxBatchApproveCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.Action,
        __ServiceName,
        "GetMaxBatchApproveCount",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Contracts.MultiToken.TokenContractImplReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS1.Acs1Reflection.Descriptor.Services[0],
          global::AElf.Standards.ACS2.Acs2Reflection.Descriptor.Services[0],
          global::AElf.Contracts.MultiToken.TokenContractReflection.Descriptor.Services[0],
          global::AElf.Contracts.MultiToken.TokenContractImplReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
    

  }
}
#endregion

