// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: token_contract_impl.proto
// </auto-generated>
// Original file comments:
// *
// MultiToken contract.
//
// The MultiToken contract is mainly used to manage the user's account and transaction fees related Settings.
// 
// Implement AElf Standards ACS1 and ACS2.
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.MultiToken {

  #region Events
  #endregion
}
#endregion

