// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vote_contract_impl.proto
// </auto-generated>
// Original file comments:
// *
// Vote contract.
//
// The Vote contract is an abstract layer for voting. Developers implement concrete voting activities 
// by calling this contract.
//
// Implement AElf Standards ACS1.
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.Vote {

  #region Events
  #endregion
  public static partial class VoteContractImplContainer
  {
    static readonly string __ServiceName = "VoteImp.VoteContractImpl";

    #region Marshallers
    static readonly aelf::Marshaller<global::AElf.Standards.ACS1.MethodFees> __Marshaller_acs1_MethodFees = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Standards.ACS1.MethodFees.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AuthorityInfo> __Marshaller_AuthorityInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AuthorityInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.VotingRegisterInput> __Marshaller_Vote_VotingRegisterInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.VotingRegisterInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.VoteInput> __Marshaller_Vote_VoteInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.VoteInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.WithdrawInput> __Marshaller_Vote_WithdrawInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.WithdrawInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.TakeSnapshotInput> __Marshaller_Vote_TakeSnapshotInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.TakeSnapshotInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.AddOptionInput> __Marshaller_Vote_AddOptionInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.AddOptionInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.RemoveOptionInput> __Marshaller_Vote_RemoveOptionInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.RemoveOptionInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.AddOptionsInput> __Marshaller_Vote_AddOptionsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.AddOptionsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.RemoveOptionsInput> __Marshaller_Vote_RemoveOptionsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.RemoveOptionsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.GetVotingItemInput> __Marshaller_Vote_GetVotingItemInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.GetVotingItemInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.VotingItem> __Marshaller_Vote_VotingItem = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.VotingItem.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.GetVotingResultInput> __Marshaller_Vote_GetVotingResultInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.GetVotingResultInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.VotingResult> __Marshaller_Vote_VotingResult = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.VotingResult.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.VotingRecord> __Marshaller_Vote_VotingRecord = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.VotingRecord.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.GetVotingRecordsInput> __Marshaller_Vote_GetVotingRecordsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.GetVotingRecordsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.VotingRecords> __Marshaller_Vote_VotingRecords = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.VotingRecords.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.VotedItems> __Marshaller_Vote_VotedItems = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.VotedItems.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.GetVotingIdsInput> __Marshaller_Vote_GetVotingIdsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.GetVotingIdsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Vote.VotedIds> __Marshaller_Vote_VotedIds = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Vote.VotedIds.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AElf.Standards.ACS1.MethodFees, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMethodFee = new aelf::Method<global::AElf.Standards.ACS1.MethodFees, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMethodFee",
        __Marshaller_acs1_MethodFees,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeMethodFeeController = new aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeMethodFeeController",
        __Marshaller_AuthorityInfo,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Standards.ACS1.MethodFees> __Method_GetMethodFee = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Standards.ACS1.MethodFees>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMethodFee",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_acs1_MethodFees);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo> __Method_GetMethodFeeController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMethodFeeController",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AuthorityInfo);

    static readonly aelf::Method<global::AElf.Contracts.Vote.VotingRegisterInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Register = new aelf::Method<global::AElf.Contracts.Vote.VotingRegisterInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Register",
        __Marshaller_Vote_VotingRegisterInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Vote.VoteInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Vote = new aelf::Method<global::AElf.Contracts.Vote.VoteInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Vote",
        __Marshaller_Vote_VoteInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Vote.WithdrawInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Withdraw = new aelf::Method<global::AElf.Contracts.Vote.WithdrawInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Withdraw",
        __Marshaller_Vote_WithdrawInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Vote.TakeSnapshotInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TakeSnapshot = new aelf::Method<global::AElf.Contracts.Vote.TakeSnapshotInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "TakeSnapshot",
        __Marshaller_Vote_TakeSnapshotInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Vote.AddOptionInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddOption = new aelf::Method<global::AElf.Contracts.Vote.AddOptionInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddOption",
        __Marshaller_Vote_AddOptionInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Vote.RemoveOptionInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveOption = new aelf::Method<global::AElf.Contracts.Vote.RemoveOptionInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveOption",
        __Marshaller_Vote_RemoveOptionInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Vote.AddOptionsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddOptions = new aelf::Method<global::AElf.Contracts.Vote.AddOptionsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddOptions",
        __Marshaller_Vote_AddOptionsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Vote.RemoveOptionsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveOptions = new aelf::Method<global::AElf.Contracts.Vote.RemoveOptionsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveOptions",
        __Marshaller_Vote_RemoveOptionsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Vote.GetVotingItemInput, global::AElf.Contracts.Vote.VotingItem> __Method_GetVotingItem = new aelf::Method<global::AElf.Contracts.Vote.GetVotingItemInput, global::AElf.Contracts.Vote.VotingItem>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVotingItem",
        __Marshaller_Vote_GetVotingItemInput,
        __Marshaller_Vote_VotingItem);

    static readonly aelf::Method<global::AElf.Contracts.Vote.GetVotingResultInput, global::AElf.Contracts.Vote.VotingResult> __Method_GetVotingResult = new aelf::Method<global::AElf.Contracts.Vote.GetVotingResultInput, global::AElf.Contracts.Vote.VotingResult>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVotingResult",
        __Marshaller_Vote_GetVotingResultInput,
        __Marshaller_Vote_VotingResult);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Vote.VotingResult> __Method_GetLatestVotingResult = new aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Vote.VotingResult>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLatestVotingResult",
        __Marshaller_aelf_Hash,
        __Marshaller_Vote_VotingResult);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Vote.VotingRecord> __Method_GetVotingRecord = new aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Vote.VotingRecord>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVotingRecord",
        __Marshaller_aelf_Hash,
        __Marshaller_Vote_VotingRecord);

    static readonly aelf::Method<global::AElf.Contracts.Vote.GetVotingRecordsInput, global::AElf.Contracts.Vote.VotingRecords> __Method_GetVotingRecords = new aelf::Method<global::AElf.Contracts.Vote.GetVotingRecordsInput, global::AElf.Contracts.Vote.VotingRecords>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVotingRecords",
        __Marshaller_Vote_GetVotingRecordsInput,
        __Marshaller_Vote_VotingRecords);

    static readonly aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.Vote.VotedItems> __Method_GetVotedItems = new aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.Vote.VotedItems>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVotedItems",
        __Marshaller_aelf_Address,
        __Marshaller_Vote_VotedItems);

    static readonly aelf::Method<global::AElf.Contracts.Vote.GetVotingIdsInput, global::AElf.Contracts.Vote.VotedIds> __Method_GetVotingIds = new aelf::Method<global::AElf.Contracts.Vote.GetVotingIdsInput, global::AElf.Contracts.Vote.VotedIds>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVotingIds",
        __Marshaller_Vote_GetVotingIdsInput,
        __Marshaller_Vote_VotedIds);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Contracts.Vote.VoteContractImplReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS1.Acs1Reflection.Descriptor.Services[0],
          global::AElf.Contracts.Vote.VoteContractReflection.Descriptor.Services[0],
          global::AElf.Contracts.Vote.VoteContractImplReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    /// <summary>Base class for the contract of VoteContractImpl</summary>

  }
}
#endregion

