namespace CAServer.Account;

public enum GuardianType
{
    GUARDIAN_TYPE_OF_EMAIL = 0,
    GUARDIAN_TYPE_OF_PHONE = 1,
    GUARDIAN_TYPE_OF_GOOGLE = 2,
    GUARDIAN_TYPE_OF_APPLE = 3,
    GUARDIAN_TYPE_OF_TELEGRAM = 4,
    GUARDIAN_TYPE_OF_FACEBOOK = 5,
    GUARDIAN_TYPE_OF_TWITTER = 6,
    GUARDIAN_TYPE_OF_TONWALLET = 7,
}